openapi: 3.0.1
info:
  title: swift rest API
  description: swift rest API built on top of light-rest-4j.
  contact:
    email: ngpari.earth@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  - url: 'http://swift.com'
paths:
  /post:
    post:
      description: post a random number
      operationId: postARandomNumber
      parameters: 
        - name: your_name
          in: query
          required: true
          description: just a random number
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
      security:
        - swiftData_auth:
            - swiftData.r
            - swiftData.w
components:
  schemas:
    SwiftData:
      type: object
      properties:
        id:
          type: string
          description: a UUID generated
        your_name:
          type: integer
          description: just a random number
        incoming_timestamp:
          type: string
        read_timestamp:
          type: string
      xml:
        name: swiftData
  securitySchemes:
    swiftData_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://localhost:8080/oauth2/code'
          scopes:
            swiftData.w: write swiftData
            swiftData.r: read swiftData

