
# Singleton service factory configuration/IoC injection
singletons:
  - com.swift.rest.service.KafkaProducerHandler:
    - com.swift.rest.service.KafkaProducerHandlerImpl
  - com.fasterxml.jackson.databind.ObjectMapper:
      - com.fasterxml.jackson.databind.ObjectMapper