
# Singleton service factory configuration/IoC injection
singletons:
  - com.swift.consumer.service.KafkaInboundHandler:
    - com.swift.consumer.service.KafkaInboundHandlerImpl
  - org.apache.kafka.common.serialization.Deserializer:
      - com.swift.consumer.serialization.SwiftDataDeserializer